<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'email file should exist' => 'файл письма должен существовать',
    'email not sent' => 'письмо не было отправлено',
    'email sent' => 'письмо отправлено',
    'email should be correct' => 'письмо должно быть правильным',
    'email should be send' => 'письмо должно быть отправлено',
    'email should contain body' => 'письмо должно содержать сообщение',
    'email should contain sender email' => 'письмо должно содержать адрес отправителя',
    'email should contain subject' => 'письмо должно содержать тему',
    'email should contain user name' => 'письмо должно содержать имя отправителя',
    'ensure login page works' => 'гарантирование работы страницы входа',
    'ensure that about works' => 'гарантирование работы страницы "О нас"',
    'ensure that contact works' => 'гарантирование работы страницы контактов',
    'ensure that home page works' => 'гарантирование работы домашней страницы',
    'ensure that signup works' => 'гарантирование работы страницы регистрации',
    'error message should be set' => 'сообщение об ошибке должно быть установлено',
    'error message should not be set' => 'сообщение об ошибке не должно быть установлено',
    'message "from" is correct' => 'сообщение "from" правильно',
    'message "to" is correct' => 'сообщение "to" правильно',
    'message file exists' => 'файл сообщений существует',
    'message has correct format' => 'сообщение имеет правильный формат',
    'message should contain correct data' => 'сообщение должно содержать правильные данные',
    'model should login user' => 'модель для залогиненного пользователя',
    'model should not login user' => 'модель для не залогиненного пользователя',
    'no user with such email, message should not be sent' => 'нет пользователя с таким email, сообщение не должно быть отправлено',
    'password should be correct' => 'пароль должен быть правильный',
    'password should be resetted' => 'пароль должен быть сброшен',
    'see that email address is wrong' => 'увидеть что email неправильный',
    'see that user is created' => 'увидеть что пользователь создался',
    'see that user is logged' => 'увидеть что пользователь залогинен',
    'see that user logged in' => 'увидеть что пользователь зарегистрирован',
    'see validations errors' => 'увидеть сведения об ошибках проверки',
    'submit contact form with correct data' => 'отправить форму контактов с правильными данными',
    'submit contact form with no data' => 'отправить форму контактов без данных',
    'submit contact form with not correct email' => 'отправить форму контактов с неправильным email',
    'submit login form with no data' => 'отправить форму входа без данных',
    'submit signup form with correct email' => 'отправить форму регистрации с правильным email',
    'submit signup form with no data' => 'отправить форму регистрации без данных',
    'submit signup form with not correct email' => 'отправить форму регистрации с неправильным email',
    'try to login with correct credentials' => 'попробовать войти с правильными учетными данными',
    'try to login with wrong credentials' => 'попробовать войти с неправильными учетными данными',
    'user has valid token' => 'пользователь имеет действительный маркер',
    'user is not active, message should not be sent' => 'пользователь не активен, то сообщение не должно быть отправлено',
    'user should be able to login with correct credentials' => 'пользователь должен иметь возможность войти в систему с правильными учетными данными',
    'user should be logged in' => 'пользователь должен быть зарегистрирован',
    'user should not be able to login with wrong password' => 'пользователь не должен иметь возможность войти с неправильным паролем',
    'user should not be able to login, when there is no identity' => 'пользователь не должен иметь возможность войти без идентификации',
    'user should not be logged in' => 'пользователь не должен быть зарегистрирован',
    'username and email are in use, user should not be created' => 'имя пользователя и email используются, пользователь не должен быть создан',
    'username should be correct' => 'имя пользователя должно быть правильным',
];
