<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Repeat password' => 'Повтор пароля',
    'A link to reset password will be sent there.' => 'Ссылка для сброса пароля будет отправлена туда.',
    'About' => 'О нас',
    'Body' => 'Сообщение',
    'Check your email for further instructions.' => 'Проверьте свою электронную почту для получения дальнейших инструкций.',
    'Contact' => 'Контакты',
    'Email' => 'Электронная почта',
    'Follow the link below to reset your password:' => 'Перейдите по ссылке ниже, чтобы сбросить пароль:',
    'Get new code' => 'Получить новый код',
    'Hello {username}' => 'Здравствуйте {username}',
    'If you forgot your password you can' => 'Если забыли свой пароль Вы можете',
    'If you have business inquiries or other questions, please fill out the following form to contact us.' => 'Если у вас есть деловое предложение или другие вопросы, пожалуйста, заполните следующую форму, чтобы связаться с нами.',
    'Incorrect username or password.' => 'Неверное имя пользователя или пароль.',
    'Login' => 'Вход',
    'Logout ({username})' => 'Выход ({username})',
    'Name' => 'Имя',
    'New password was saved.' => 'Новый пароль сохранен.',
    'Password' => 'Пароль',
    'Password reset for {appname}' => 'Восстановление пароля для {appname}',
    'Password reset token cannot be blank.' => 'Маркер сброса пароля не может быть пустым.',
    'Please choose your new password:' => 'Пожалуйста, выберите новый пароль:',
    'Please contact us if you think this is a server error.' => 'Пожалуйста свяжитесь с нами если вы считаете что это ошибка сервера.',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Please fill out the following fields to signup:' => 'Пожалуйста, заполните следующие поля, чтобы зарегистрироваться:',
    'Please fill out your email.' => 'Пожалуйста, заполните Вашу электронную почту.',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'Send' => 'Отправить',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'К сожалению, мы не можем сбросить пароль для предоставленной электронной почты.',
    'Subject' => 'Тема',
    'Thank you for contacting us.' => 'Благодарим Вас за обращение к нам.',
    'Thank you.' => 'Спасибо.',
    'The above error occurred while the Web server was processing your request.' => 'Произошла ошибка при запросе страницы.',
    'There is no user with such email.' => 'Нет ни одного пользователя с такой электронной почтой.',
    'There was an error sending email.' => 'Произошла ошибка при отправке электронной почты.',
    'This email address has already been taken.' => 'Этот адрес электронной почты уже зарегистрирован.',
    'This username has already been taken.' => 'Это имя пользователя уже зарегистрировано.',
    'Up' => 'Наверх',
    'Username' => 'Имя пользователя',
    'Verification Code' => 'Проверочный код',
    'We will respond to you as soon as possible.' => 'Мы ответим Вам как можно скорее.',
    'Wrong password reset token.' => 'Неправильный маркер сброса пароля.',
    'reset it' => 'восстановить его',
    '{appname} robot' => '{appname} робот',
];
