<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"findIdentityByAccessToken" is not implemented.' => '"findIdentityByAccessToken" не реализован.',
    'Congratulations!' => 'Поздравляем!',
    'Get started with Yii' => 'Начало работы с Yii',
    'Heading' => 'Заголовок',
    'This is the About page.' => 'Это страница "О нас"',
    'Yii Documentation' => 'Yii документация',
    'Yii Extensions' => 'Yii расширения',
    'Yii Forum' => 'Yii форум',
    'You have successfully created your Yii-powered application.' => 'Вы успешно создали свое приложение на Yii.',
    'You may modify the following file to customize its content:' => 'Вы можете изменить следующий файл, чтобы настроить содержание:',
];
